#!/usr/bin/env bash
# Export the controller environment for ansible-playbook.
#
# Reads ONLY the allow-listed keys from the ignored root .env. The file is
# parsed line by line — never sourced or evaluated — and values are never
# printed. Values already present in the caller's environment win.
set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

ENV_FILE="${GT_ENV_FILE:-${ROOT_DIR}/.env}"
ALLOWED_KEYS=(VAULT_LICENSE RHSM_ORG RHSM_ACTIVATION_KEY RHEL_DNS_SERVERS GT_IMAGE)

load_env_file() {
  local line key value allowed
  [[ -f "${ENV_FILE}" ]] || return 0
  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ "${line}" =~ ^[[:space:]]*(#|$) ]] && continue
    [[ "${line}" =~ ^[[:space:]]*(export[[:space:]]+)?([A-Z_][A-Z0-9_]*)=(.*)$ ]] || continue
    key="${BASH_REMATCH[2]}"
    value="${BASH_REMATCH[3]}"
    for allowed in "${ALLOWED_KEYS[@]}"; do
      [[ "${key}" == "${allowed}" ]] || continue
      # Strip one pair of surrounding quotes, if present.
      if [[ "${value}" =~ ^\"(.*)\"$ || "${value}" =~ ^\'(.*)\'$ ]]; then
        value="${BASH_REMATCH[1]}"
      fi
      if [[ -z "${!key:-}" ]]; then
        export "${key}=${value}"
      fi
    done
  done <"${ENV_FILE}"
}

prepare_local_dirs
load_env_file

# The Terraform inventory plugin needs absolute paths (its binary lookup is
# broken on ansible-core 2.21 unless binary_path is set), so the plugin config
# is generated per machine into the ignored cache.
TF_BIN="$(command -v terraform || true)"
if [[ -n "${TF_BIN}" ]]; then
  cat >"${CACHE_DIR}/ansible/inventory/terraform.yml" <<INVENTORY
# Generated by scripts/ansible-env.sh — do not edit.
plugin: cloud.terraform.terraform_provider
project_path: ${TF_DIR}/infra
binary_path: ${TF_BIN}
INVENTORY
fi

export ANSIBLE_CONFIG="${ROOT_DIR}/ansible.cfg"
export ANSIBLE_LOCAL_TEMP="${CACHE_DIR}/ansible/tmp"
export ANSIBLE_COLLECTIONS_PATH="${CACHE_DIR}/ansible/collections"
export ANSIBLE_GALAXY_TOKEN_PATH="${CACHE_DIR}/ansible/galaxy_token"
# Absolute paths: the baseline playbook also runs as a subprocess of
# `terraform -chdir=terraform/infra apply`, whose working directory differs.
export ANSIBLE_ROLES_PATH="${ROOT_DIR}/ansible/roles"
export ANSIBLE_CALLBACK_PLUGINS="${ROOT_DIR}/ansible/plugins/callback"
# gt_stats writes the recap counts of a phase here (GT_PHASE set by ansible-run.sh).
export GT_STATS_DIR="${BUILD_DIR}/ansible-stats"
if [[ -f "${TF_DIR}/infra/terraform.tfstate" ]]; then
  export ANSIBLE_INVENTORY="${ROOT_DIR}/ansible/inventory/localhost.yml,${CACHE_DIR}/ansible/inventory/terraform.yml"
else
  export ANSIBLE_INVENTORY="${ROOT_DIR}/ansible/inventory/localhost.yml"
fi
